version: 2

models:
  - name: stg_airbnb
    description: Staging model for Airbnb listings.

    columns:
      - name: id
        tests:
          - unique
          - not_null

      - name: host_id
        tests:
          - not_null

      - name: room_type
        tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                  - "Entire Home/apt"
                  - "Private Room"
                  - "Shared Room"

  - name: dim_host
    description: Host Dimension

    columns:
      - name: host_id
        tests:
          - unique
          - not_null

  - name: fact_listings
    description: Listings Fact

    columns:
      - name: id
        tests:
          - unique
          - not_null

      - name: host_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_host')
                field: host_id